sudo: required
dist: trusty

language: go

go:
  - 1.5.3

before_install:
  - sudo ./preinstall.sh

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - go test -v -short -cover -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
