sudo: required
dist: trusty

language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

before_install:
  - sudo GO_VERSION=skip ./preinstall.sh

install:
  - # Do nothing.

script:
  - go get -t -v ./... github.com/mattn/goveralls
  - go test -v -short -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...

after_success:
  - for dir in ./format ./thumbnail ./cmd/fotomat; do go test -short -cover -covermode=count -coverprofile=$dir/profile.out $dir; done
  - (echo mode:\ count; find ./ -name profile.out | xargs grep -vh mode:\ count ) > all.out
  - goveralls -coverprofile=all.out -service=travis-ci
