language: go

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

go:
  - 1.5.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./preinstall.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/vips; fi

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - go test -v -short -cover -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
